"""empty message

Revision ID: 1686a9b29fce
Revises: c7112e04bf3c
Create Date: 2019-05-13 01:14:50.583886

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1686a9b29fce'
down_revision = 'c7112e04bf3c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('sid', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'sid')
    # ### end Alembic commands ###
