"""empty message

Revision ID: 7a45251d2499
Revises: 1686a9b29fce
Create Date: 2019-05-13 01:18:31.045298

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7a45251d2499'
down_revision = '1686a9b29fce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('college', sa.String(length=50), nullable=True))
    op.add_column('user', sa.Column('phone', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'phone')
    op.drop_column('user', 'college')
    # ### end Alembic commands ###
