"""empty message

Revision ID: c7112e04bf3c
Revises: 
Create Date: 2019-05-13 00:39:53.604691

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c7112e04bf3c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.Column('gender', sa.SmallInteger(), nullable=False),
    sa.Column('grade', sa.Integer(), nullable=True),
    sa.Column('major', sa.String(length=50), nullable=True),
    sa.Column('class_name', sa.String(length=50), nullable=True),
    sa.Column('face_url', sa.String(length=200), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('openid', sa.String(length=100), nullable=True),
    sa.Column('unionid', sa.String(length=100), nullable=True),
    sa.Column('is_bind_jw', sa.Boolean(), nullable=False),
    sa.Column('avatar', sa.String(length=200), nullable=False),
    sa.Column('city', sa.String(length=30), nullable=True),
    sa.Column('province', sa.String(length=30), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('update_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('unionid')
    )
    op.create_table('notice',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('update_time', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('notice')
    op.drop_table('user')
    # ### end Alembic commands ###
